name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022
    env:
      CMAKE_PREFIX_PATH: ${{ github.workspace }}\.local
    steps:
    - uses: actions/checkout@v2

    - name: Install Catch2
      run: |
        git clone --branch v2.x https://github.com/catchorg/Catch2
        cmake -S Catch2 -B Catch2/build -DBUILD_TESTING=OFF -DCMAKE_INSTALL_PREFIX="$env:CMAKE_PREFIX_PATH"
        cmake --build Catch2/build --target install

    - name: Configure CMake
      run: cmake -S . -B build
        
    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: |
        cd build
        ctest -C Release

    - name: Install
      run: cmake --install build --config Release --prefix "$env:CMAKE_PREFIX_PATH"

    - name: Configure CMake for examples
      run: cmake -S examples -B examples\build

    - name: Build examples
      run: cmake --build examples\build --config Release
