name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022
    env:
      CMAKE_PREFIX_PATH: ${{ github.workspace }}\.local
    steps:
    - uses: actions/checkout@v2

    - name: Install Catch2
      run: |
        vcpkg integrate install
        vcpkg install catch2:x64-windows

    - name: Configure CMake
      run: cmake -S . -B build "-DCMAKE_TOOLCHAIN_FILE=$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake"
        
    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: |
        cd build
        ctest -C Release

    - name: Install
      run: cmake --install build --config Release --prefix "$env:CMAKE_PREFIX_PATH"

    - name: Configure CMake for examples
      run: cmake -S examples -B examples\build

    - name: Build examples
      run: cmake --build examples\build --config Release
