name: Windows Build

on:
  push:
    branches: [ msvc-action ]
  pull_request:
    branches: [ msvc-action ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Install Catch2
      run: |
        vcpkg integrate install
        vcpkg install catch2:x64-windows
    
    - name: Configure CMake
      run: |
        echo "${env:VCPKG_INSTALLATION_ROOT}"
        
      #run: cmake -B ${{github.workspace}}\build -DCMAKE_TOOLCHAIN_FILE=${env:VCPKG_INSTALLATION_ROOT}\scripts\buildsystems\vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}\build

    - name: Test
      working-directory: ${{github.workspace}}\build
      run: ctest
      
